apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: proyecto
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    app: proyecto-deployment
