apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-sfs
  namespace: proyecto
spec:
  selector:
    matchLabels:
      app: postgresql-a # has to match .spec.template.metadata.labels
  serviceName: postgresql-svc
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: postgresql-a # has to match .spec.selector.matchLabels
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox:1.36
        command: ["sh", "-c", "mkdir -p /var/lib/postgresql/data && chmod -R 777 /var/lib/postgresql/data"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data          
      containers:
        - name: postgresql-db
          image: postgres
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata           
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: proyecto-secreto
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: proyecto-secreto
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: proyecto-secreto
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
              name: postgresql-port
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi