apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: proyecto-deployment-update
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      authorName: flux
      authorEmail: flux@example.com
    push:
      branch: main
  interval: 1m
  update:
    strategy: Setters